# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=1000)),
                ('location_address', models.CharField(max_length=1000)),
                ('location_locality', models.CharField(max_length=1000)),
                ('location_city', models.CharField(max_length=1000)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('restaurant_cuisine', models.CharField(max_length=1000)),
                ('restaurant_avgcostfor2', models.IntegerField()),
                ('restaurant_thumb', models.CharField(max_length=1000)),
                ('user_rating_agg', models.FloatField()),
                ('user_rating_vote', models.FloatField()),
                ('res_id', models.IntegerField()),
            ],
        ),
    ]
