# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkRest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=1000)),
                ('location_address', models.CharField(max_length=1000)),
                ('location_locality', models.CharField(max_length=1000)),
                ('location_city', models.CharField(max_length=1000)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('restaurant_cuisine', models.CharField(max_length=1000)),
                ('restaurant_avgcostfor2', models.IntegerField()),
                ('restaurant_thumb', models.CharField(max_length=1000)),
                ('user_rating_agg', models.FloatField()),
                ('user_rating_vote', models.FloatField()),
                ('res_id', models.IntegerField()),
                ('is_bookmarked', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
