# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_bookmarkrest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkrest',
            name='is_bookmarked',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
