# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkhomeservices',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='bookmarkhomeservices',
            old_name='location_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='homeservices',
            old_name='location_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='homeservices',
            old_name='location_longitude',
            new_name='longitude',
        ),
    ]
