# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0002_auto_20160929_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='close_time',
            field=models.CharField(default='1000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='contact',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='latitude',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='longitude',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='open_now',
            field=models.CharField(default='1000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkhomeservices',
            name='open_time',
            field=models.CharField(default='1000', max_length=1000, null=True),
        ),
    ]
