# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0003_auto_20160930_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkhomeservices',
            name='type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homeservices',
            name='type',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
