# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0004_auto_20160930_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
