# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0005_picture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='close_time',
            field=models.CharField(default='2000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeservices',
            name='open_now',
            field=models.CharField(default='True', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homeservices',
            name='open_time',
            field=models.CharField(default='1000', max_length=1000, null=True),
        ),
    ]
