# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservices', '0006_auto_20161004_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='rating',
            field=models.CharField(default='3', max_length=1000, null=True),
        ),
    ]
