# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('contact_no', models.IntegerField()),
                ('size_bhk', models.CharField(max_length=50)),
                ('rent_price', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=4000)),
                ('tenure', models.CharField(max_length=500)),
                ('sqft_area', models.IntegerField()),
                ('house_logo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_logo', models.FileField(upload_to=b'')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseonrent.House')),
            ],
        ),
    ]
