# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseonrent', '0002_bookmarkhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('rent_price', models.IntegerField()),
                ('advance_pymt', models.IntegerField()),
                ('config', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='house',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='pic_logo',
        ),
        migrations.AddField(
            model_name='picture',
            name='house_thumb',
            field=models.CharField(default='sdaodnalds', max_length=1000),
            preserve_default=False,
        ),
    ]
