# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseonrent', '0003_auto_20160926_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Houses',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='contact_no',
            new_name='advance_pymt',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='location',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='house',
            name='description',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_logo',
        ),
        migrations.RemoveField(
            model_name='house',
            name='size_bhk',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sqft_area',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tenure',
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(default='0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(default='0.0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_price',
            field=models.IntegerField(),
        ),
    ]
