# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseonrent', '0004_auto_20160926_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_pic',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
