# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houseonrent', '0006_auto_20160926_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('rent_price', models.IntegerField()),
                ('advance_pymt', models.IntegerField()),
                ('config', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('house_pic', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
