# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='opt_entered',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
