# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161005_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='opt_entered',
            new_name='otp_entered',
        ),
    ]
