# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161005_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_verified',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
