# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 17:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('category', models.TextField(max_length=100)),
                ('no_of_posts', models.IntegerField()),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated_time', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
