# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20161005_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='no_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
