# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkfurniture',
            name='close_time',
            field=models.CharField(default='2000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='close_time',
            field=models.CharField(default='2000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='open_now',
            field=models.CharField(default='True', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='open_time',
            field=models.CharField(default='1000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='rating',
            field=models.CharField(default='3', max_length=1000, null=True),
        ),
    ]
